sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t dokumansky/ssl-proxy -f Dockerfile .
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "ssl-proxy"
  env: "ssl-proxy-env"
  bucket_name: "elasticbeanstalk-us-west-2-730376649188"
  bucket_path: "ssl-proxy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
