version : '3'
services :
  server:
    build :
      context: '.'
      dockerfile : Dockerfile.dev
    ports :
      - '80:80'
      - '443:443'
    volumes :
      - /usr/app/node_modules
      - .:/app
    environment:
      - DEBUG=1