# specify the node base image with your desired version node:<version>
FROM node:12.19.0-alpine3.10
# replace this with your application's default port

WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY ./ ./
CMD ["npm","start"]